Initial setup of apps page
storjrd/iris pull request #158
Opened 2021-07-02 18:05 UTC by gabedealmeida

2021-07-02 18:35 UTC, super3 commented
@gabedealmeida Looks like both buttons are selected when you click backup.

![Capture](https://user-images.githubusercontent.com/60975/124315861-a7888a80-db42-11eb-8cf5-e831f53e5ad8.PNG)

2021-07-02 19:47 UTC, super3 approved these changes
Tested any everything looks good here.

2021-07-02 22:44 UTC, montyanderson requested changes

2021-07-02 22:44 UTC, montyanderson commented on ui/src/store/account.js
> +			accessKey: "4EdkanJHIlJ8949JIk23jlfjaJNallfH90",
What are these keys?

2021-07-05 15:32 UTC, super3 commented on ui/src/store/account.js
> +			accessKey: "4EdkanJHIlJ8949JIk23jlfjaJNallfH90",
Those are dummy keys for now.

2021-07-05 15:34 UTC, super3 requested changes
Need to make the backup page functional. It is ok if the usage page is not functional at this time.

2021-07-06 15:44 UTC, montyanderson approved these changes

2021-07-06 15:44 UTC, super3 approved these changes

2021-07-06 15:44 UTC, merged